# This is the name of the workflow, visible on GitHub UI.
name: test
on: [push, pull_request]
jobs:
  compile-sketch:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: arduino/compile-sketches@v1
        with:
          sketch-paths: |
           - ./
          libraries: |
            # none
            -
